{
    "message": "Bad Request", // (or "Validation error" if generated by Sequelize),
    "errors": {
      "page": "Page must be greater than or equal to 1",
      "size": "Size must be greater than or equal to 1",
    "maxLat": "Maximum latitude is invalid",
    "minLat": "Minimum latitude is invalid",
    "maxLng": "Maximum longitude is invalid",
    "minLng": "Minimum longitude is invalid",
      "minPrice": "Minimum price must be greater than or equal to 0",
      "maxPrice": "Maximum price must be greater than or equal to 0"
    }
  }
